### ISSUE TITLE
Installing SloppyCell

### ISSUE THREAD

**Issue by rjpbonnal** [GutenkunstLab/SloppyCell#7]
Dear SloppyCell developers,
do you have a working procedure to install SloppyCell, preferably using conda?

Bests,
R

**Comment by thelahunginjeet** [comment]
I've got a lecacy python 2.7 environment for this purpose, but there's no way I used to conda to install. Very likely just distutils (did it so long ago I can't really remember). Sorry I can't be more help.

KB

**Comment by RyanGutenkunst** [comment]
Hi Kevin,

FYI: Bryan Daniels got SloppyCell ported to Python 3.x, if you ever need it: https://github.com/GutenkunstLab/SloppyCell .

Best,
Ryan

> On Oct 2, 2023, at 10:41 AM, Kevin Brown ***@***.***> wrote:
> 
> External Email
> 
> 
> I've got a lecacy python 2.7 environment for this purpose, but there's no way I used to conda to install. Very likely just distutils (did it so long ago I can't really remember). Sorry I can't be more help.
> 
> KB
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

--
Ryan Gutenkunst
Professor and Interim Department Head
Department of Molecular and Cellular Biology, University of Arizona
phone: (520) 626-0569, office: LSS 325, web: http://gutengroup.arizona.edu

**Comment by thelahunginjeet** [comment]
Thanks Ryan - glad to know it didn't just die.

**Comment by sbalasbas3** [comment]
I am also having trouble with installing SloppyCell.

These are what I have in my own local Anaconda environment:

Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
NumPy version: 2.1.3
SciPy version: 1.14.1
Matplotlib version: 3.9.2

And when I try to install SloppyCell, I get the following error indicating the necessity to have `numpy.distutils`. I do not know how to resolve this:

```
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\users\sbalasbasiii\downloads\sloppycell-master\sloppycell-master\setup.py", line 2, in <module>
          import numpy.distutils.core as core
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Would you recommend downgrading to a previous version of either numpy or Python? I also get problems when doing that.

**Comment by RyanGutenkunst** [comment]
numpy.distutils has been deprecated: https://numpy.org/devdocs/reference/distutils_status_migration.html . From that page, it seems like your best bet is to downgrade to at least Python 3.11. Unfortunately, my group does not have the bandwidth to migrate SloppyCell to a more modern build system. Maybe @bcdaniels does?
